use super::*;

pub type OApiCallback<
    PathItemExt,
    ParameterExt,
    ServerExt,
    ServerVarExt,
    ExampleExt,
    MediaTypeExt,
    HeaderExt,
    EncodingExt,
    LinkExt,
    RequestExt,
    ResponseExt,
    CallbackExt,
    ExternalDocExt,
    ObjectExt,
    ArrayExt,
    NumericExt,
    StringExt,
    DiscriminatorExt,
> = HashMap<
    String,
    OApiPathItem<
        PathItemExt,
        ParameterExt,
        ServerExt,
        ServerVarExt,
        CallbackExt, // Replace the Operation extension with the callback
        ExampleExt,
        MediaTypeExt,
        HeaderExt,
        EncodingExt,
        LinkExt,
        RequestExt,
        ResponseExt,
        CallbackExt,
        ExternalDocExt,
        ObjectExt,
        ArrayExt,
        NumericExt,
        StringExt,
        DiscriminatorExt,
    >,
>;
